services:
  app:
    container_name: laravel_app
    build:
      context: ./exemple-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./exemple-app:/app"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl:/etc/nginx/ssl"
    depends_on:
      - db
  db:
    container_name: laravel_db
    image: mariadb:11.3
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_USER: root
      MARIADB_PASSWORD: debian
      MARIADB_ROOT_PASSWORD: debian
    ports:
      - "3308:3306"
    volumes:
       - "./sql-scripts:/docker-entrypoint-initdb.d"
       - dbdata:/var/lib/mysql

  dbpy:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atd
      MYSQL_USER: atduser
      MYSQL_PASSWORD: atdpassword
    volumes:
      - dbdatapy:/var/lib/mysql
      - ./ticketing/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s

  pyapp:
    build:
      context: ./ticketing
      dockerfile: Dockerfile
    depends_on:
      dbpy:
        condition: service_healthy
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
volumes:
  dbdatapy:
  dbdata:
